inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'test/*.rb'
  SuggestExtensions: false
Layout/HashAlignment:
  Exclude:
    - '*.gemspec'
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Gemspec/AddRuntimeDependency: # style
  Enabled: false
